[images]
  remote_images = [
    "https://ext.same-assets.com/236577210/*.jpeg",
    "https://ext.same-assets.com/236577210/*.png",
    "https://ext.same-assets.com/236577210/*.woff"
  ]

[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
